version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE=iot_manager
      - USER=postgres
      - PASSWORD=postgres
      - HOST=db
      - PORT=5432

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: iot_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"